package com.easy.easyai.tools.shell

import com.easy.easyai.core.agent.AgentContext
import com.easy.easyai.core.agent.AgentService
import com.easy.easyai.core.permission.PermissionAction
import com.easy.easyai.core.permission.PermissionRule
import com.easy.easyai.core.permission.ToolPermissionEvaluator
import com.easy.easyai.core.tool.ScriptEnvProvider
import com.easy.easyai.core.tool.ToolBuilder
import com.easy.easyai.core.tool.ToolDefinition
import com.easy.easyai.core.tool.ToolMetadata
import org.springframework.beans.factory.annotation.Autowired
import org.springframework.stereotype.Component
import java.nio.file.Path

/**
 * Builder for [BashTool].
 */
@Component
class BashToolBuilder(
    @param:Autowired(required = false)
    private val scriptEnvProvider: ScriptEnvProvider? = null
) : ToolBuilder {
    override val metadata = ToolMetadata(
        name = "bash",
        description = """Execute a shell command in the current working directory.
Do NOT use this tool for:
- File content search: use grep instead
- File name matching (find): use glob instead
- Directory listing (ls): use ls instead
- Reading files (cat/head/tail): use read instead
- One-off numeric/date/time formulas (no data files involved): use calc instead
- Single file ≤ 512KB calculations: use calc with filePath parameter instead
DO use this tool for:
- Multiple files: write a Python or JavaScript script to process them
- Single file > 512KB: write a Python or JavaScript script and run it
- Calculations requiring third-party libraries (pandas, numpy, etc.)
Error handling:
- NEVER redirect stderr to /dev/null (2>/dev/null). stderr contains critical diagnostic info (e.g. "command not found"). Suppressing it makes failures invisible.
- In pipelines, the exit code is from the LAST command by default. A failing command early in the pipe will be masked. Use "set -o pipefail;" prefix if you need true error propagation.
- If a command produces no output, do NOT assume success. Check exit code and retry without stderr suppression.
Parameters:
- timeout (optional): Idle timeout in seconds (10-600, default 300). Timer resets on output; process is killed only when idle for this duration.""",
        permissionCategory = "shell",
        tracksFileChanges = true,
        uiRenderer = "bash",
        patternKeys = listOf("command", "cmd")
    )
    override val permissionEvaluator = ToolPermissionEvaluator { ctx ->
        ctx.sharedEvaluator.evaluateShellPermission(ctx.rules, ctx.projectPath, ctx.arguments)
    }
    override val defaultPermissionRules = listOf(
        PermissionRule("shell.safe", "*", PermissionAction.ALLOW),
        PermissionRule("file.read.project", "*", PermissionAction.ALLOW),
        PermissionRule("file.write.project", "*", PermissionAction.ALLOW)
    )
    override val rulePermissionType = "shell.other"

    override fun build(context: AgentContext, agentService: AgentService): ToolDefinition {
        val workDir = context.projectPath ?: Path.of(".")
        // Probe the user's login shell env once (cached) so that commands like
        // mvn/node/go resolve correctly even when Spring Boot was launched from
        // an IDE or systemd with an incomplete PATH.
        val baseEnv = ShellEnvProbe.probe()
        // Reuse scriptEnv from AgentContext (already generated by ChatStreamService),
        // fall back to provider for contexts that bypass ChatStreamService (e.g. swarm).
        val scriptEnv = context.scriptEnv.ifEmpty {
            scriptEnvProvider?.getScriptEnv(context) ?: emptyMap()
        }
        val mergedEnv = (baseEnv + scriptEnv).ifEmpty { null }
        return BashTool(metadata, workDir, mergedEnv)
    }
}
