export interface Attachment {
  id: string;
  name: string;
  mimeType: string;
  /** Base64-encoded content. Present for clipboard images and legacy attachments. */
  data: string;
  size: number;
  /** Absolute local file path. Present for uploaded/local files. */
  filePath?: string;
}

/** Checkpoint data attached to an assistant message after file changes are committed */
export interface MessageCheckpoint {
  messageId?: string;
  snapshotHash?: string;
  filesChanged: string[];
  additions: number;
  deletions: number;
}

export interface UserMessage {
  role: 'user' | 'user-with-attachments';
  content: string;
  timestamp: number;
  /** Backend message ID for edit functionality */
  messageId?: string;
  attachments?: Attachment[];
  /** Timestamp when this message was compacted (undefined = not compacted) */
  compactedAt?: number;
  /** Metadata from backend (e.g., source: 'steering' | 'follow_up' | 'completion_check') */
  metadata?: Record<string, string>;
}

/**
 * Tool call information in an assistant message.
 * Does NOT include result or status — those come separately:
 * - status: via SSE ToolCallStatusEvent during streaming
 * - result: via ToolResultMessage (role: 'tool')
 */
export interface ToolCall {
  id: string;
  toolName: string;
  args: string;
  /** Optional content blocks if tool returned structured data */
  contentBlocks?: ToolResultContentBlock[];
}

/**
 * Content block types for tool result parsing.
 * Matches backend ContentBlock sealed interface.
 */
export type ToolResultContentBlock = 
  | TextContentBlock
  | ToolResultContentBlockData;

export interface TextContentBlock {
  type: 'text';
  text: string;
}

export interface ToolResultContentBlockData {
  type: 'toolResult';
  toolCallId: string;
  toolName: string;
  output: string;
  exitCode?: number | null;
  durationMs?: number | null;
  mimeType?: string;
  isError?: boolean;
  truncated?: boolean;
  /** Token usage from this tool execution (e.g., sub-agent LLM calls) */
  usage?: {
    inputTokens: number;
    outputTokens: number;
    totalTokens: number;
    cacheReadTokens?: number;
    cacheWriteTokens?: number;
    durationMs?: number;
  };
}

/**
 * Parsed tool result from a tool execution.
 * Associated with a ToolCall via matching id.
 */
export interface ToolResult {
  id: string;
  toolName: string;
  result: string;
  /** Parsed content blocks from JSON result string */
  contentBlocks?: ToolResultContentBlock[];
  isError: boolean;
  exitCode?: number | null;
  durationMs?: number | null;
  mimeType?: string | null;
  truncated?: boolean;
  /** Token usage from this tool execution (e.g., sub-agent LLM calls) */
  usage?: {
    inputTokens: number;
    outputTokens: number;
    totalTokens: number;
    cacheReadTokens?: number;
    cacheWriteTokens?: number;
    durationMs?: number;
  };
}

/** Reference to a memory entry injected into the system prompt */
export interface MemoryRef {
  name: string;
  description: string;
  type: string;
  scope: string;
}

/** Reference to a rule file (e.g., AGENTS.md) injected into the system prompt */
export interface RuleRef {
  name: string;
  source: string;
}

/** Context references that were injected into an assistant message's system prompt */
export interface ContextReferences {
  memories: MemoryRef[];
  rules: RuleRef[];
}

export interface AssistantMessage {
  role: 'assistant';
  messageId?: string;
  content: string;
  thinking?: string;
  toolCalls?: ToolCall[];
  toolResults?: ToolResult[];
  /** Stop reason from backend: STOP, TOOL_USE, ABORTED, LENGTH, ERROR */
  stopReason?: string;
  usage?: {
    inputTokens: number;
    outputTokens: number;
    totalTokens: number;
    cacheReadTokens?: number;
    cacheWriteTokens?: number;
    durationMs?: number;
  };
  /** Thinking block duration in ms (from backend) */
  thinkingDurationMs?: number;
  /** Text block duration in ms (from backend) */
  textDurationMs?: number;
  timestamp: number;
  /** Timestamp when this message was compacted (undefined = not compacted) */
  compactedAt?: number;
  /** Sub-agent messages nested under this message (loaded from history) */
  subAgentMessages?: SubAgentMessageGroup[];
  /** Checkpoint data if this turn produced file changes */
  checkpoint?: MessageCheckpoint;
  /** Context references (memories and rules) used in this response */
  references?: ContextReferences;
}

/**
 * Group of messages generated by a sub-agent during a tool call.
 */
export interface SubAgentMessageGroup {
  toolCallId: string;
  agentName: string;
  messages: Message[];
}

/**
 * Custom content block for extensible message types.
 * Used for system-level metadata like compaction indicators.
 */
export interface CustomContentBlock {
  type: 'custom';
  customType: string;
  metadata?: {
    compactedCount?: number;
    tokensSaved?: number;
    compactedAt?: number;
    summaryMessageId?: string;
    [key: string]: unknown;
  };
}

/**
 * Tool result message.
 * Contains the output of tool execution, sent with role: 'tool'.
 */
export interface ToolResultMessage {
  role: 'tool';
  toolResults: ToolResult[];
  timestamp: number;
}

/**
 * Custom message for system-level indicators.
 * Not displayed in conversation flow - used for UI indicators like compaction.
 */
export interface CustomMessage {
  role: 'custom';
  customType: string;
  metadata: {
    compactedCount?: number;
    tokensSaved?: number;
    compactedAt?: number;
    summaryMessageId?: string;
    isCompactionIndicator?: boolean;
    [key: string]: unknown;
  };
  timestamp: number;
}

export interface ErrorMessage {
  role: 'error';
  content: string;
  timestamp: number;
  messageId?: string;
}

export type Message = UserMessage | AssistantMessage | ToolResultMessage | ErrorMessage | CustomMessage;

/**
 * A message queued for later delivery to the agent (steering or follow-up).
 * Lives in the frontend store until consumed by the agent loop.
 */
export interface QueuedMessage {
  /** Locally generated temporary ID (before backend sync). */
  id: string;
  /** Message content text. */
  content: string;
  /** Queue type: steer is injected at next turn, followUp after current response completes. */
  type: 'steer' | 'followUp';
  /** Backend queue ID returned after successful sync. Undefined until synced. */
  backendQueueId?: string;
  /** Sync status with backend. */
  status: 'pending' | 'syncing' | 'synced' | 'failed';
  /** Image attachments associated with this queued message. */
  attachments?: Attachment[];
}