<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>com.easy</groupId>
        <artifactId>easyai-autoconfigure</artifactId>
        <version>${revision}</version>
    </parent>
    <artifactId>easyai-web-autoconfigure</artifactId>
    <packaging>jar</packaging>
    <name>EasyAI Web Autoconfigure</name>

    <dependencies>
        <dependency>
            <groupId>com.easy</groupId>
            <artifactId>easyai-api</artifactId>
        </dependency>
        <dependency>
            <groupId>com.easy</groupId>
            <artifactId>easyai-core</artifactId>
        </dependency>
        <dependency>
            <groupId>com.easy</groupId>
            <artifactId>easyai-web</artifactId>
        </dependency>
        <dependency>
            <groupId>com.easy</groupId>
            <artifactId>easyai-tools</artifactId>
        </dependency>
        <dependency>
            <groupId>com.easy</groupId>
            <artifactId>easyai-core-autoconfigure</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-autoconfigure</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-configuration-processor</artifactId>
            <optional>true</optional>
        </dependency>
        <dependency>
            <groupId>org.jetbrains.kotlin</groupId>
            <artifactId>kotlin-test</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>com.easy</groupId>
            <artifactId>easyai-observability</artifactId>
        </dependency>
        <dependency>
            <groupId>com.easy</groupId>
            <artifactId>easyai-snapshot</artifactId>
        </dependency>
    </dependencies>

</project>