<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>com.easy</groupId>
        <artifactId>easyai-agent</artifactId>
        <version>${revision}</version>
    </parent>
    <artifactId>easyai-agent-coding</artifactId>
    <packaging>jar</packaging>
    <name>EasyAI Agent Coding Tools</name>

    <dependencies>
        <dependency>
            <groupId>com.easy</groupId>
            <artifactId>easyai-agent-core</artifactId>
            <version>${revision}</version>
        </dependency>
        <dependency>
            <groupId>com.easy</groupId>
            <artifactId>easyai-tools</artifactId>
        </dependency>
    </dependencies>
</project>