<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>com.easy</groupId>
        <artifactId>easyai</artifactId>
        <version>${revision}</version>
    </parent>
    <artifactId>easyai-common</artifactId>
    <packaging>pom</packaging>
    <name>EasyAI Common Parent</name>

    <modules>
        <module>easyai-common-bom</module>
        <module>easyai-common-core</module>
        <module>easyai-common-util</module>
        <module>easyai-common-textio</module>
    </modules>

    <properties>
        <kotlin.version>2.3.10</kotlin.version>
    </properties>

    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>com.easy</groupId>
                <artifactId>easyai-common-core</artifactId>
                <version>${revision}</version>
            </dependency>
            <dependency>
                <groupId>com.easy</groupId>
                <artifactId>easyai-common-util</artifactId>
                <version>${revision}</version>
            </dependency>
            <dependency>
                <groupId>com.easy</groupId>
                <artifactId>easyai-common-textio</artifactId>
                <version>${revision}</version>
            </dependency>
        </dependencies>
    </dependencyManagement>
</project>
